### PR TITLE
First pass at making RemoteKernelManager independent

### PR DESCRIPTION
**Pull request by golf-player**
This is a WiP.

So first pass, I just wanted to get things working, and they do (with nbclient, not sure if gatewayapp still works, but it should). There's way too much asking for permission in the code right now, and there's probably a lot that could be done to separate code where mappingkernelmanagers are needed. Another option is to make a single kernel mapping manager (AKA a completely useless stupid class) just for convenience.

What do you think about doing traitlets like this? To properly share it with EG App, I'll need to add this mixin and remove the included traitlets from EG App.

### CODE REVIEW

**Comment by kevin-bates** [comment]
Thanks for submitting the pull request.  

I'd rather not take the trailet approach as this will break existing configurations.  Is there an issue with a property/accessor approach?

> There's way too much asking for permission in the code right now

Can you elaborate on this?  Are you referring to `if` statements?

> Another option is to make a single kernel mapping manager (AKA a completely useless stupid class) just for convenience.

You're welcome to use something like this in your wrapper code, but probably doesn't belong in EG.  So the idea would be to set a placeholder for `parent` and `parent.parent` items?

I think the kernelspec issue you brought up on #803 is something we need to address before proceeding.

**Comment by golf-player** [comment]
I guess the only problem with the property approach is that it's a lot of repeated code. How does using traitlets like this break configuration? I'm not too familiar with traitlets.

> Can you elaborate on this? Are you referring to if statements?
Yeah basically there's too many points where we're checking if a property exists before doing something, when IMO there should be a clear divide between things that use a MultiKernelManager (MKM) and not (of course, this may be less useful if my use case isn't a common one). Or maybe that code belongs in the kernel_manager class.

> So the idea would be to set a placeholder for parent and parent.parent items?

The idea there would be to continue as is, removing parent and parent.parent items. `parent` is an MKM, so making something with the same interface, which basically is no-op on things like kernel connection count increments and then setting that as a property on RKM, which in this pull request is `RKM.multi_kernel_manager`. that code could live anywhere, true.

> I think the kernelspec issue you brought up on #803 is something we need to address before proceeding.

The problem being that the processproxy RKM uses is ignoring config from the kernelspec, right?

**Comment by golf-player** [comment]
One thing I don't like is calling out to uuid.uuid4, but I see that done in several other places as well. Do you think it would make sense to make a function for everything to use, or keep it here, since technically the way RKM sets kernel_id should be agnostic of everything else.

**Comment by kevin-bates** [comment]
Do you mind moving the conversation back to the issue?  I'm getting scattered with a bunch of other stuff going on and I'm kinda wondering if we should try to jump on a web session to get on the same page here.  Would you be available for something like that? If so, please drop me a note on my github email and I'll forward you a link.

**Comment by golf-player** [comment]
I was going to ask about switching back to the issue haha.

I'll send you an email

File: enterprise_gateway/services/kernels/remotemanager.py [hunk 1]
```diff
@@ -12,9 +12,11 @@
 from ipython_genutils.importstring import import_item
 from notebook.services.kernels.kernelmanager import MappingKernelManager
 from jupyter_client.ioloop.manager import IOLoopKernelManager
+from traitlets import log as traitlets_log
 
 from ..processproxies.processproxy import LocalProcessProxy, RemoteProcessProxy
 from ..sessions.kernelsessionmanager import KernelSessionManager
+from enterprise_gateway.mixins import EnterpriseGatewayConfigMixin
```
Comment (golf-player) [inline enterprise_gateway/services/kernels/remotemanager.py:19]: Do y'all have an opinion on relative vs absolute imports? Mixing is bad, so I'll probably change this. That said, I really don't like the `...mixins` import

File: enterprise_gateway/services/kernels/remotemanager.py [hunk 2]
```diff
@@ -418,8 +434,30 @@ def _get_process_proxy(self):
            instantiated.
         """
         process_proxy_cfg = get_process_proxy_config(self.kernel_spec)
+        print(self.kernel_spec)
         process_proxy_class_name = process_proxy_cfg.get('class_name')
         self.log.debug("Instantiating kernel '{}' with process proxy: {}".
                        format(self.kernel_spec.display_name, process_proxy_class_name))
         process_proxy_class = import_item(process_proxy_class_name)
         self.process_proxy = process_proxy_class(kernel_manager=self, proxy_config=process_proxy_cfg.get('config'))
+
```
Comment (golf-player) [inline enterprise_gateway/services/kernels/remotemanager.py:440]: So looking into the code, seems kernelspec manager is already handled by the base class of RKM, and it gets invoked the same way as the one attached to RMKM

**Comment by golf-player** [comment]
TODO: Fix tests, add tests, squash into nice commit

**Comment by golf-player** [comment]
OK got it to work with mixins. A tag hacky maybe.

File: enterprise_gateway/services/kernels/remotemanager.py [hunk 3]
```diff
@@ -325,26 +355,28 @@ def restart_kernel(self, now=False, **kwargs):
...
         """
         self.restarting = True
-        kernel_id = os.path.basename(self.connection_file).replace('kernel-', '').replace('.json', '')
+        kernel_id = self.kernel_id or os.path.basename(self.connection_file).replace('kernel-', '').replace('.json', '')
         # Check if this is a remote process proxy and if now = True. If so, check its connection count. If no
         # connections, shutdown else perform the restart.  Note: auto-restart sets now=True, but handlers use
         # the default value (False).
-        if isinstance(self.process_proxy, RemoteProcessProxy) and now:
-            if self.parent._kernel_connections.get(kernel_id, 0) == 0:
+        if isinstance(self.process_proxy, RemoteProcessProxy) and now and self.mapping_kernel_manager:
```
Comment (kevin-bates) [inline enterprise_gateway/services/kernels/remotemanager.py:362]: Good catch on mapping_kernel_manager's potential for null.

File: enterprise_gateway/services/kernels/remotemanager.py [hunk 4]
```diff
@@ -423,3 +455,24 @@ def _get_process_proxy(self):
                        format(self.kernel_spec.display_name, process_proxy_class_name))
         process_proxy_class = import_item(process_proxy_class_name)
         self.process_proxy = process_proxy_class(kernel_manager=self, proxy_config=process_proxy_cfg.get('config'))
+
+    @property
```
Comment (kevin-bates) [inline enterprise_gateway/services/kernels/remotemanager.py:459]: I think we should add a comment block somewhere (thinking prior to these properties) that talks about when `self.parent` would not exist.  This might warrant an entry in the docs as well - although I don't mind keeping this on the down-low for the time being. :wink:

File: enterprise_gateway/services/kernels/remotemanager.py (hunk 1 above)
Comment (golf-player) [reply enterprise_gateway/services/kernels/remotemanager.py:19]: I retract that actually. Mixing is guaranteed to happen when you're using relative imports mostly given some of them are going to need a lot of dots. It's a cosmetic concern at worst.

File: enterprise_gateway/enterprisegatewayapp.py [hunk 5]
```diff
@@ -56,7 +54,7 @@
 })
 
 
-class EnterpriseGatewayApp(JupyterApp):
+class EnterpriseGatewayApp(JupyterApp, EnterpriseGatewayConfigMixin):
```
[the remark this answers is not in the document]
Comment (golf-player) [reply enterprise_gateway/enterprisegatewayapp.py:57]: Good catch.

File: enterprise_gateway/services/kernels/remotemanager.py [hunk 6]
```diff
@@ -224,6 +233,27 @@ def __init__(self, **kwargs):
         if hasattr(self, "cache_ports"):
             self.cache_ports = False
 
+        if not self.connection_file and not self.kernel_id:
```
[the remark this answers is not in the document]
Comment (golf-player) [reply enterprise_gateway/services/kernels/remotemanager.py:236]: good catch. I'll remove the line setting it to None since it doesn't really help.

File: enterprise_gateway/services/kernels/remotemanager.py (hunk 4 above)
Comment (golf-player) [reply enterprise_gateway/services/kernels/remotemanager.py:459]: Will do. Is there somewhere specific in the docs where something like this might go?

File: enterprise_gateway/services/kernels/remotemanager.py [hunk 7]
```diff
@@ -224,6 +233,27 @@ def __init__(self, **kwargs):
...
+            return
+        dependent_props = ["authorized_users",
+                           "unauthorized_users",
+                           "port_range",
+                           "impersonation_enabled",
+                           "max_kernels_per_user",
+                           "env_whitelist",
+                           "env_process_whitelist",
+                           ]
+        self._links = [directional_link((eg_instance, prop), (self, prop)) for prop in dependent_props]
```
[the remark this answers is not in the document]
Comment (golf-player) [reply enterprise_gateway/services/kernels/remotemanager.py:255]: This is a traitlets thing actually. Any reason to not be a fan? I kind of like the ability to explicitly tie certain attributes to an upstream source.

File: enterprise_gateway/services/kernels/remotemanager.py (hunk 4 above)
Comment (kevin-bates) [reply enterprise_gateway/services/kernels/remotemanager.py:468]: I'm okay deferring this for now, although if we were to add it, the following locations might be worthy of updates:
- We should add an entry (or two?) to [Use Cases](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/use-cases.html#use-cases)
- Perhaps add the details to the end of the deployments section (following [IBM Spectrum Conductor](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/kernel-conductor.html#ibm-spectrum-conductor))

I'm trying to think of what we'd call the topic.  The term "Library Mode" popped into my head just now.  I'm not enamored with that, but I'd like the topic to convey a more direct capability that utilizes the heart of EG.  "Integration Mode" - something that allows third-parties to use RMK directly.  Ideas welcome! 

The topic should include an example - much like the one you opened the issue with - based on the final results.  (Btw, I'd like to have those details anyway so I could try things out against my Hadoop YARN cluster.)

Comment (golf-player) [reply enterprise_gateway/services/kernels/remotemanager.py:468]: I like library mode. Just anything that conveys the meaning that this is JEG but without the gateway webapp.

Standalone Remote Kernel Execution if verbosity isn't an issue. 

The example actually becomes really simple.

```
import nbformat
from nbclient import NotebookClient
from enterprise_gateway.services.kernels.remotemanager import RemoteKernelManager

with open("/home/ish/notebooks/Untitled.ipynb") as fp:
    test_notebook = nbformat.read(fp, as_version=4)

client = NotebookClient(nb=test_notebook, kernel_manager_class=RemoteKernelManager)
client.execute()
```

If you'd like a full docker with kernelspecs and config, I can do that, but I don't have experience with Yarn so it may take a while.

Comment (kevin-bates) [reply enterprise_gateway/services/kernels/remotemanager.py:468]: I like "Standalone Remote Kernel Execution" as the topic.  Perhaps in the opening statement, we can toss in an "a.k.a., Library Mode". :smile: This way we have a way to quickly identify the context when communicating this functionality or discussing it in general.

The sample is excellent - I'm really happy with how this is turning out.  Let's not worry about a docker image for the moment. Given the example, I can run this against my YARN cluster, although probably not today (sorry).

**Comment by kevin-bates** [comment]
Hi - I finally got around to trying this, and I'm not able to make it off the launch pad.  Using nbclient 0.1.0 (0.2.0 switches to async kernel management, which EG isn't able to move to yet due to notebook), I get the following because `self.kernel_spec_manager` is None. 
```
python -m indieRMK.py 
Traceback (most recent call last):
  File "/opt/anaconda2/envs/py3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda2/envs/py3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/gateway/indieRMK.py", line 9, in <module>
    client.execute()
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/nbclient/client.py", line 357, in execute
    with self.setup_kernel(**kwargs):
  File "/opt/anaconda2/envs/py3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/nbclient/client.py", line 339, in setup_kernel
    self.start_new_kernel_client(**kwargs)
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/nbclient/client.py", line 312, in start_new_kernel_client
    self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs)
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 274, in start_kernel
    self._get_process_proxy()
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 458, in _get_process_proxy
    process_proxy_cfg = get_process_proxy_config(self.kernel_spec)
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/jupyter_client/manager.py", line 84, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
AttributeError: 'NoneType' object has no attribute 'get_kernel_spec'
```
Are you using a config file of any sorts to set that up?  I was able to run EG fine with this build, but get this in 'library mode'.  My driver is essentially identical to your [example code](https://github.com/jupyter/enterprise_gateway/pull/810#discussion_r418412886).

Also, I think we're going to want some form of documentation for this.  We're you still planning on adding that?

**Comment by golf-player** [comment]
@kevin-bates apologies for getting back to you so late. Got wrapped up in another project. I will have time this week to debug this issue. I'm guessing it's the nbclient version difference; I'm using the latest nbclient (which works I guess surprisingly, given JEG isn't async)

What's the timeline for the JEG deploy btw? I may be able to reprioritize things depending in order to have this ready by then if possible.

I will be writing documentation for this.

**Comment by kevin-bates** [comment]
Hi @golf-player - thanks for the update.  Regarding the timeline, as soon as Notebook 6.1 is available, we will merge #794 and start building the next EG release.  I'm hopeful that some of the front-end notebook issues will be reviewed/merged in the next week or two so that release can move forward.

I would love to get this into the next EG release, so, should things get to that point, I don't mind waiting to ensure this is ready, although I don't expect that to be necessary.

**Comment by golf-player** [comment]
Looks like nbclient 0.3.0 also just dropped. I've gotten both 0.3.0 and 0.1.0 to _run_ the kernel, but there's another issue creeping up on both versions where they're not shutting down the kernels after.

Will update the MR for now with the changes to just add a kernelspec_manager in the constructor if one isn't gotten from the parent (RMKM explicitly passes a kernelspec_manager)

**Comment by kevin-bates** [comment]
@golf-player - thanks for the updates.  I took this for another spin against my YARN cluster and got the following...
```
Traceback (most recent call last):
  File "/opt/anaconda2/envs/py3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda2/envs/py3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/gateway/indieRMK.py", line 9, in <module>
    client.execute()
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/nbclient/client.py", line 357, in execute
    with self.setup_kernel(**kwargs):
  File "/opt/anaconda2/envs/py3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/nbclient/client.py", line 339, in setup_kernel
    self.start_new_kernel_client(**kwargs)
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/nbclient/client.py", line 312, in start_new_kernel_client
    self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs)
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 279, in start_kernel
    self._get_process_proxy()
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 468, in _get_process_proxy
    self.process_proxy = process_proxy_class(kernel_manager=self, proxy_config=process_proxy_cfg.get('config'))
  File "/opt/anaconda2/envs/py3/lib/python3.6/site-packages/enterprise_gateway/services/processproxies/yarn.py", line 44, in __init__
    kernel_manager.parent.parent.yarn_endpoint)
AttributeError: 'NoneType' object has no attribute 'parent'
```
I went ahead and added a few more entries to `dependent_props` and was then able to run a notebook using nbclient.  I had nbclient 0.1.0 installed and noticed the kernel had not been terminated.  However, after updating to 0.2.0, I found the kernel terminated, but with a state of `KILLED`...
image
when "graceful" termination should produce a state of `FINISHED`.  This implies that the something isn't quite right with the shutdown sequence.  You might not see this using k8s, but it would be good to understand the why the message-based termination is not occurring.

In the YARN application log, we should see a shutdown indicator like the last line here.  Instead, we see all but that line.
```
Log Type: stdout
Log Upload Time: Sat May 16 07:20:33 -0700 2020
Log Length: 1772

[D 2020-05-16 07:17:44,825.825 launch_ipykernel] Using connection file '/tmp/kernel-6e7f4f81-1ffc-4c09-8a3b-0920f7fd2272_I_lTUb.json'.
[I 2020-05-16 07:17:44,826.826 launch_ipykernel] Signal socket bound to host: 0.0.0.0, port: 50501
[D 2020-05-16 07:17:44,830.830 launch_ipykernel] JSON Payload '{"stdin_port": 44132, "pgid": "3249", "ip": "0.0.0.0", "pid": "3299", "control_port": 47874, "hb_port": 40748, "signature_scheme": "hmac-sha256", "key": "cfc3a76f-964f-4f87-9bc8-1cbaaf8dd39f", "comm_port": 50501, "kernel_name": "", "shell_port": 53084, "transport": "tcp", "iopub_port": 39304}
[D 2020-05-16 07:17:44,836.836 launch_ipykernel] Encrypted Payload 'u5T6rmMK+4S6e659vVYcSooB9AA+yQhmrIXbTXBaMBdNjVGV3KaNTi1wHvxxLHZ/4J4xnw3j8ARbyEx0qEJ53LRUsphakrvh+IG2UtRloSgR9oBO+tUKf9LfXC0XHzorxuEdTr/byIEcQ6ChHgqqkxT4qnzum/TASyf8+MV3LBxW5M6gteoeTFeibvqD4hKa6UQm/A7+QT+aabxP5/flD1hPXPA+2AbDwSLyoLQpu+wHagihjEH6BqcH9YfuZ7ihErRQp4xb0ignUZRu7xvdvpg+KntBzq/rWvnlmLP+t9SUnc2/72pEJ6cYxat3SLpfg8ZsHUzhBlk8lJVlo9l0j6dqX7t+jDNzcUEwj/bL2Mk0E0RlQseb5IqDWcKYzjJjpYaooA8aOieLM3+zm6t8hg==

[I 2020-05-16 07:20:33,493.493 launch_ipykernel] gateway_listener got request: {u'shutdown': 1}
```

I've pushed the `parent.parent` removal to my repo - feel free to grab them or I can push to yours.  https://github.com/kevin-bates/enterprise_gateway/tree/remove-parent-parent

**Comment by kevin-bates** [comment]
Looking at nbclient 0.2.0, if I add this line following [L335](https://github.com/jupyter/nbclient/blob/0.2.0/nbclient/client.py#L332-L349)
```
await ensure_async(self.km.shutdown_kernel(now=False))
```
I get a graceful shutdown with a `FINISHED` status.

**Comment by golf-player** [comment]
Sorry about that, I didn't go through the other processproxy subclasses. 

Seems like the problem here is that graceful shutdown (kernel client shutdown) isn't shutting down the process. 

Looking into it.

**Comment by kevin-bates** [comment]
The process is shutdown but nbclient isn't giving the kernel manager an initial chance to do it gracefully. This is a difference in behavior from what notebook does.

**Comment by golf-player** [comment]
https://github.com/jupyter/nbclient/blob/0.2.0/nbclient/client.py#L334-335

Here the client is given the chance to shutdown gracefully rather than the manager

**Comment by kevin-bates** [comment]
Right. This was my very comment from earlier today: https://github.com/jupyter/enterprise_gateway/pull/810#issuecomment-630270703

**Comment by golf-player** [comment]
Sorry I'm a bit confused here. Is `self.kc.shutdown` not the correct way to shut down a kernel?

**Comment by kevin-bates** [comment]
That sends the shutdown message to the kernel, but we leverage the kernel manager for interacting with the hosting resource manager and the shutdown method on the kernel manager includes both graceful and immediate options.

For the graceful route we send a comparable shutdown request to the listener but for immediate we enlist the help of the resource manager to do whatever is necessary. On YARN that equates to calling their KILL API.

**Comment by golf-player** [comment]
So in the case of a docker container running a kernel process, the kernel gets the shutdown message, and at that point the process should exit 0, stopping the running container. 

I guess what's happening here is that the kill request happens while it's shutting down. I'm still trying to see that that's what's happening in the logs

**Comment by golf-player** [comment]
Yeah that's what's happening; the shutdown message is received, then the pod gets killed.

**Comment by kevin-bates** [comment]
We have the listener as well. It's a sibling to the kernel to handle things like interrupts. I haven't looked at the container process proxies lately but they probably terminate the container when the immediate route is taken. This is probably ok in container land but not in YARN where the status is killed rather than finished.

**Comment by golf-player** [comment]
i think this warrants a discussion of its own with the nbclient devs. nbclient 0.3.0 I believe also does a force shutdown

> This is probably ok in container land but not in YARN where the status is killed rather than finished.

Agreed. distributed mode as well. And even in container land, if it's being `KILL`ed, it's possible some things don't stop gracefully, like [shutdown hooks](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.hooks.html#IPython.core.hooks.shutdown_hook)

**Comment by golf-player** [comment]
https://github.com/jupyter/nbclient/issues/60

**Comment by kevin-bates** [comment]
Thanks @golf-player.  I guess I'm okay with the docs.  They're really just an example and the code won't change even after nbclient fixes things.  At most I guess we'd update the nbclient version in the example, but since there's already 0.3.0, even that isn't a big deal.

I guess one of us should submit a PR to nbclient if we don't hear back from them soon.

Aside from that, how are we doing here?  Was the conductor endpoint commit the test-fix you were referring to?

**Comment by golf-player** [comment]
Well as of nbclient 0.3.1, it works at least as well as 0.2.0, so that's good.

I'm working on a rough implementation to get some conversation going with them.

I think this PR is looking done more or less. Yeah it was a minor config change breaking tests, but no issues now.

**Comment by kevin-bates** [comment]
Sounds good. Thanks for opening the nbclient PR.

I just ran this both as EG and Independent RMK (like [Independent George](https://www.youtube.com/watch?v=3afZip4BTRc)) and things look great.  I plan on performing a squash and merge first thing tomorrow.  If you'd prefer to squash to get the comment as you'd like please feel free, otherwise, I'll likely leave the meaningful commit comments in place or derive one myself.

I think is going to be really useful!  Thank you.

**Comment by golf-player** [comment]
I've pushed a squashed commit. 

Thanks so much for all the help! Hopefully the nbclient PR goes well.

File: docs/source/kernel-library.md [hunk 8]
```diff
@@ -0,0 +1,22 @@
+## Standalone Remote Kernel Execution 
+#####a.k.a "Library Mode"
```
Comment (kevin-bates) [inline docs/source/kernel-library.md:2]: Shoot - just noticed this needs a space between the heading and `a.k.a`.

Comment (golf-player) [reply docs/source/kernel-library.md]: Ugh my bad...

I blame pycharm.

This is fixed.
